apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  annotations:
    description: Add Lab VLAN 1924 and Bridge br-1924 on ens224
  name: ens224-v1924
spec:
  desiredState:
    interfaces:
      - ipv4:
          enabled: false
        ipv6:
          enabled: false
        name: ens224
        state: up
        type: ethernet
      - ipv4:
          enabled: false
        ipv6:
          enabled: false
        name: ens224.1924
        state: up
        type: vlan
        vlan:
          base-iface: ens224
          id: "1924"
      - bridge:
          options:
            stp:
              enabled: false
          port:
            - name: ens224.1924
              vlan: {}
        ipv4:
          enabled: false
        ipv6:
          enabled: false
        name: br-1924
        state: up
        type: linux-bridge
  nodeSelector:
    machine.openshift.io/cluster-api-machineset: hub-fpkcn-cnv