---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  spec: # null for all ipaddresspools instead
    ipAddressPools:
      - lab-192-168-4-224-b29
