---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clusters

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: example-ssh-key
    files:
      - secrets/ssh-publickey

  - name: example-pull-secret
    type: kubernetes.io/dockerconfigjson
    files:
      - secrets/.dockerconfigjson

resources:
- hostedcluster.yaml
- namespace.yaml
- nodepool.yaml
