apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clusters

resources:
  - ../../base

components:
  - ../../components/network

# the inline patch will not learn of the random suffix, so disable it :(
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: cloudinitdisk-rhel-node
    files:
      - scripts/userData

patches:
- target:
    group: kubevirt.io
    kind: VirtualMachine
    name: rhel-node-1
    version: v1
  patch: |-
    - op: replace
      path: /spec/template/spec/volumes/1/cloudInitNoCloud
      value: {"secretRef":{"name":"cloudinitdisk-rhel-node"}}
    - op: replace
      path: /spec/running
      value: true